# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: WEBGames Beta
email: ...
description: > # this means to ignore newlines until "baseurl:"
  Play games, free! Some games will not work on work or school networks. Our games sometimes use cookies. Some games are online, and require a internet connection. Some games are blocked by your browser; on chrome- go to the to right side of the url box, and load unsafe script. NOTE: This will disable secure Htpps connection. We are not responsible for any damage on your electronic device.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Jorti1boomox
github_username:  jorti1

# Build settings
markdown: kramdown

theme: jekyll-theme-slate
